"""Hindsight's declared config surface — rendered by the generic desktop panel."""

from plugins.memory.config_schema import (
    KIND_SECRET,
    KIND_SELECT,
    KIND_TEXT,
    ProviderConfigSchema,
    ProviderField,
    ProviderFieldOption,
)

CONFIG_SCHEMA = ProviderConfigSchema(
    name="hindsight",
    label="Hindsight",
    fields=(
        ProviderField(
            key="mode",
            label="Mode",
            kind=KIND_SELECT,
            default="cloud",
            description="How Hermes connects to Hindsight.",
            options=(
                ProviderFieldOption(
                    "cloud",
                    "Cloud",
                    "Hindsight Cloud API (lightweight, just needs an API key)",
                ),
                ProviderFieldOption(
                    "local_embedded",
                    "Local Embedded",
                    "Run a managed local Hindsight daemon with embedded PostgreSQL (needs LLM API key)",
                ),
                ProviderFieldOption(
                    "local_external",
                    "Local External",
                    "Connect to an existing Hindsight instance",
                ),
            ),
            inline=True,
        ),
        ProviderField(
            key="api_key",
            label="Cloud API key",
            kind=KIND_SECRET,
            env_key="HINDSIGHT_API_KEY",
            description="Hindsight Cloud API key (cloud mode only).",
            placeholder="Enter Hindsight Cloud API key",
            inline=True,
        ),
        ProviderField(
            key="llm_api_key",
            label="LLM API key",
            kind=KIND_SECRET,
            env_key="HINDSIGHT_LLM_API_KEY",
            description="LLM API key for memory extraction (local embedded mode).",
            placeholder="Enter LLM API key",
            inline=True,
        ),
        ProviderField(
            key="llm_provider",
            label="LLM provider",
            kind=KIND_SELECT,
            default="openai",
            description="LLM provider for local embedded mode.",
            options=(
                ProviderFieldOption("openai", "openai"),
                ProviderFieldOption("anthropic", "anthropic"),
                ProviderFieldOption("gemini", "gemini"),
                ProviderFieldOption("groq", "groq"),
                ProviderFieldOption("openrouter", "openrouter"),
                ProviderFieldOption("minimax", "minimax"),
                ProviderFieldOption("ollama", "ollama"),
                ProviderFieldOption("lmstudio", "lmstudio"),
                ProviderFieldOption("openai_compatible", "openai_compatible"),
            ),
            inline=True,
        ),
        ProviderField(
            key="llm_base_url",
            label="LLM base URL",
            kind=KIND_TEXT,
            description="OpenAI-compatible endpoint URL (for openai_compatible provider).",
            env_fallbacks=("HINDSIGHT_API_LLM_BASE_URL",),
            inline=True,
        ),
        ProviderField(
            key="llm_model",
            label="LLM model",
            kind=KIND_TEXT,
            default="gpt-4o-mini",
            description="Model name for LLM calls (e.g. gpt-4o-mini, glm-5.2-heavy).",
            inline=True,
        ),
        ProviderField(
            key="api_url",
            label="API URL",
            kind=KIND_TEXT,
            default="https://api.hindsight.vectorize.io",
            aliases=("apiUrl",),
            env_fallbacks=("HINDSIGHT_API_URL",),
            inline=True,
        ),
        ProviderField(
            key="bank_id",
            label="Bank ID",
            kind=KIND_TEXT,
            default="hermes",
            aliases=("bankId",),
            inline=True,
        ),
        ProviderField(
            key="recall_budget",
            label="Recall budget",
            kind=KIND_SELECT,
            default="mid",
            aliases=("budget",),
            options=(
                ProviderFieldOption("low", "low"),
                ProviderFieldOption("mid", "mid"),
                ProviderFieldOption("high", "high"),
            ),
            inline=True,
        ),
    ),
)
